### ISSUE TITLE
Installing on RStudio in Ubuntu 18.04

### ISSUE THREAD

**Issue by tiagocabaco** [sakrejda/parse-stan#3]
Dear @sakrejda , 

I am trying to install stannis from RStudio and I always run into this error:

`install_github("sakrejda/stannis")`

`Note: wrong number of arguments to '==' `
`Note: wrong number of arguments to '!=' `
`Error: package or namespace load failed for ‘stannis’ in namespaceExport(ns, exports):`
`undefined exports: label, name_margins`

Thank you for your help, 

Tiago

**Comment by sakrejda** [comment]
Hi, I just reproduced this and fixed it on the 'master' branch so that the devtools install should work now.  It looks like some people are starting to try the package so I'll stop breaking the master branch.

**Comment by sakrejda** [comment]
Please let me know/re-open if there are other show-stopper issues.  Some of the interface is not all that well documented but I'm hoping to standardize that soon.

**Comment by tiagocabaco** [comment]
Hi, thank you it is fixed now! 

By the way, is there some reason I can't use the read_cmdstan_csv command? 

Do I have to compile from source? 

Thanks,

**Comment by sakrejda** [comment]
The reader commands are in c++ so they do have to be compiled but I'm not sure how it would install if it doesn't compile so... not sure.  I was in the middle of trying some experimental things when it seems like a few people started trying the package out so.  Can you file a separate issue that shows what the failure looks like? If you can show the failure with `options(error=recover)` and post the output it gives you when it fails that's helpful to me.  I'd like to clean these things up and clarify which features are solid and which are experimental.
